### ISSUE TITLE
readme steps 2 & 3 elaboration

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-project-cookiecutter#14]
Users don't need to reinstall poetry if they already have it

`poetry --version`

See also https://python-poetry.org/history/

`poetry self update` if desired

What should the response to the `poetry init` questions be?

**Comment by turbomam** [comment]
are you sure that `poetry install` is required after adding the older version of `click`?

**Comment by turbomam** [comment]
Any reason the two-line step 3 shouldn't be

```shell
poetry run cruft create https://github.com/linkml/linkml-project-cookiecutter
```

**Comment by turbomam** [comment]
What is the `google_analytics_gtag` for?

**Comment by turbomam** [comment]
Clarify in the readme or the cruft script:

github_token_for_pypi_deployment [PYPI_PASSWORD]

just defines the name of the GH secret that our actions will be looking for

**Comment by pkalita-lbl** [comment]
This appears to be based on the instructions prior to https://github.com/linkml/linkml-project-cookiecutter/pull/84. 

`google_analytics_gtag` was removed from the setup questions in https://github.com/linkml/linkml-project-cookiecutter/pull/24

I believe `github_token_for_pypi_deployment` is now sufficiently explained in the README.

Closing
