### ISSUE TITLE
python classes are not generated

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-project-cookiecutter#17]
It looks like the Makefile is supposed to generate some `*.py` files in `project/` when running the `gen-project` CLI tool as part of the `gen-project` rule. No `gen-project` --include or --exclude options are provided.

Then those Python files are supposed to be copied to the schema's `datamodel` directory.

Presumably, the Python files in the `datamodel` directory would then get published to PyPI as part of a GH release. But these Python files are never generated, moved or published.

```make
DEST = project

PYMODEL = $(SRC)/$(SCHEMA_NAME)/datamodel

all: site
site: gen-project gendoc

gen-project: $(PYMODEL) compile-sheets
	$(RUN) gen-project -d $(DEST) $(SOURCE_SCHEMA_PATH) && mv $(DEST)/*.py $(PYMODEL)
```

**Comment by turbomam** [comment]
Although the logs make it seem like the python generation does happen:

> INFO:root:Generating: python
INFO:root: SCHEMA: src/synbio_schema/schema/synbio_schema.yaml
INFO:root: PARENT=project
INFO:root: python ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: project/synbio_schema.py

Maybe something unexpected is happening during the `mv` step ?

**Comment by turbomam** [comment]
The Makefile rule expands to 

```shell
poetry run gen-project -d project src/synbio_schema/schema/synbio_schema.yaml && mv project/*.py src/synbio_schema/datamodel
```

**Comment by turbomam** [comment]
And that does generate something along the lines of `project/synbio_schema.py` (depending on the repo of course)

**Comment by cmungall** [comment]
To confirm your hypothesis that something is happening in the mv step can
you should the full logging or at least the part with the mv step?

Note the cleanest thing to do here is for genp to just put things in the
right place to start with
