### ISSUE TITLE
"make test" runs gen-project but puts outputs in /tmp - causing "make test" to continue to fail without an updated python class

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml-project-cookiecutter#19]
steps to reproduce:

1) create a project using linkml-project-cookiecutter
2) make a breaking change to the schema yaml file
3) run `make test` (noting that the test still works even with the breaking yaml change)

some solutions might be:
- do something complicated in the test_data.py so that we import from the regenerated /tmp directory? 
- overwrite the python in src/linkml_tutorial_schema/datamodel directory with the refreshed classes that were generated into /tmp?

**Comment by cpauvert** [comment]
Hi @sierra-moxon 
How was this issue resolved and what is the recommend approach? Because I also ran into the same problem.
Best,
