### ISSUE TITLE
Shouldn't cruft-based actions in repos built with this template be wrapped in poetry?

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-project-cookiecutter#30]
```Makefile
update-template:
	poetry run cruft update
```

In the Makefile, instead of 

```Makefile
update-template:
	cruft update
```

**Comment by pkalita-lbl** [comment]
They should not. Following the current recommendation, if you've installed `cruft` with `pipx` then `cruft update` should work just fine. I've you've chosen to go the `pipx run cruft ...` route that's perfectly fine, but I think it's up to the end user to adjust their Makefile accordingly at that point.
