### ISSUE TITLE
poetry install complaining not a git project

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml-project-cookiecutter#33]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/50745/207416516-a2eb0267-852b-424a-87b1-bf5e5447b81d.png">

**Comment by hrshdhgd** [comment]
I created a new project from scratch using this cookiecutter and I could not reproduce this error. Could this be a old poetry version issue?

**Comment by StroemPhi** [comment]
I just encountered the same error, when setting up a new repo from scratch according to the readme and also had to `git init`in order to be able to run `make setup`.

**Comment by hrshdhgd** [comment]
Closing via #38
