### ISSUE TITLE
passing custom args to gen-xxx tools

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml-project-cookiecutter#51]
There is no method to customize  `gen-xxx` commands invoked by gen-project. For example, we cannot pass  `--no-metaclasses` to `gen-owl` via the Makefile.  Here in this project, I suggest solving the problem using environment variables like #43 as this scales well.

**Comment by noelmcloughlin** [comment]
See #52 for proposed solution (for gen-owl)

**Comment by cmungall** [comment]
Actually, there is a way to pass these in

Unfortunately it's not obvious as if you do `gen-metadata` from the command line the formatting is messed up; see:

 - #1216.  

So what you want is:

config.yaml:
```yaml
generator_args: 
  owl: 
     metaclasses: false
```

the whole system is a little unsatisfying - in general in linkml we eat our own dogfood, and we would have a complete schema for all configuration. However, the click annotations are the source-of-truth for anything CLI, so the yaml here is a kind of jury rigged layer on top of multiple separate click files. I'm not sure there is a much better way to do it without a big revamp. But it could certainly be better documented!

**Comment by noelmcloughlin** [comment]
Thanks. Do you mean we can drop `config.xml` into linkml-project-cookiecutter home directory (and github-actions workflow directory) and gen-xxx will read that file?

**Comment by nlharris** [comment]
Can this be merged or closed?

**Comment by noelmcloughlin** [comment]
Yes thanks - fixed in #67
