### ISSUE TITLE
.decode error running make setup

### ISSUE THREAD

**Issue by samwalrus** [linkml/linkml-project-cookiecutter#73]
I got this error twice when running make setup:

AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'? 

With chat gpts help it said "Since strings in Python 3.x are already decoded (i.e., they are Unicode), they don't have a decode() method." and it told meto remove the .decode calls from line 127 owlgen.py and line 47 in shaclgen.py in my  ~//.cache/pypoetry/virtualenvs/.. folders and then the make setup ran ok.

**Comment by juliomateoslangerak** [comment]
Same issue in shaclgen.py

**Comment by jonathanunderwood** [comment]
This is due to https://github.com/linkml/linkml/issues/1567

Fix for now is to pin to version 6 of rdflib. See #75 for a PR implementing that - it's a simple fix you can apply locally in the meantime.

**Comment by pkalita-lbl** [comment]
https://github.com/linkml/linkml/issues/1567 was fixed with LinkML 1.6.3 so you should no longer see this error when setting up a new project.
