### ISSUE TITLE
document disadvantages of poetry's curl | python3 installation suggestion

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-project-cookiecutter#80]
- security risk: takes unknown bytes from some web address and pipes them through an interpreter
- loss of control regarding installation directory

I'm still inclined to use this piping installation approach, but maybe we should make this decision process more transparent, and not imply that it is globally a prudent installation method

**Comment by pkalita-lbl** [comment]
This project's instructions now reflect Poetry's own recommendation which is to install with `pipx`.
